const mongoose = require('mongoose');

const auditLogSchema = new mongoose.Schema({
  action: { type: String, enum: ['CREATED', 'UPDATED', 'DELETED', 'RECONCILED'], required: true },
  timestamp: { type: Date, default: Date.now },
  performedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  notes: { type: String }
}, { _id: true });

const transactionSchema = new mongoose.Schema({
  transactionNumber: { 
    type: String, 
    unique: true, 
    sparse: true,
    required: false // Generated by service layer if not provided
  },
  type: { 
    type: String, 
    enum: ['Income', 'Expense', 'Transfer'], 
    required: [true, 'Transaction type is required'] 
  },
  amount: { 
    type: Number, 
    required: [true, 'Amount is required'],
    min: [0.01, 'Amount must be greater than zero']
  },
  category: { 
    type: String, 
    required: [true, 'Transaction category is required'],
    trim: true
  }, // e.g. 'Order Payment', 'Raw Material', 'Salaries', 'Supplies', 'Utilities', 'Maintenance', 'Marketing', 'Other'
  paymentMethod: { 
    type: String, 
    enum: ['Cash', 'UPI', 'Bank Transfer', 'Card', 'Cheque'], 
    required: [true, 'Payment method is required'],
    default: 'Cash'
  },
  date: { 
    type: Date, 
    default: Date.now,
    index: true
  },
  description: { 
    type: String,
    trim: true,
    default: '' 
  },
  referenceId: { 
    type: String,
    trim: true,
    index: true 
  }, // e.g. Bill No., Invoice Number, Receipt ID
  orderRef: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Order',
    index: true 
  },
  customerRef: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Customer',
    index: true
  },
  employeeRef: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  recordedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  status: {
    type: String,
    enum: ['Completed', 'Pending', 'Cancelled'],
    default: 'Completed'
  },
  auditLog: [auditLogSchema]
}, { 
  timestamps: true 
});

// Explicit composite database indexes for reporting and search query performance
transactionSchema.index({ type: 1, date: -1 });
transactionSchema.index({ category: 1, date: -1 });
transactionSchema.index({ paymentMethod: 1 });
transactionSchema.index({ description: 'text', category: 'text', referenceId: 'text' });

module.exports = mongoose.model('Transaction', transactionSchema);
